### ISSUE TITLE
Unable to build Demo project - The "ResolveBlazorRuntimeDependencies" task failed unexpectedly

### ISSUE THREAD

**Issue by bkv143** [isc30/blazor-lazy-loading#22]
Unable to build Demo solution. The build process failed with error:

Error	MSB4018	The "ResolveBlazorRuntimeDependencies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'WasmHost.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'WasmHost.dll' ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Microsoft.AspNetCore.Components.WebAssembly.Build.ResolveBlazorRuntimeDependencies.ResolveRuntimeDependenciesCore(String entryPoint, IEnumerable`1 applicationDependencies, IEnumerable`1 monoBclAssemblies)
   at Microsoft.AspNetCore.Components.WebAssembly.Build.ResolveBlazorRuntimeDependencies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

	WasmHost	C:\Users\BKV\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Blazor.MonoRuntime.targets	324

**Comment by isc30** [comment]
Marking this as closed, feel free to open another issue if still having problems building the project.
